config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :gossips
  resources :users
  resources :cities
  resources :comments
  resources :sessions
  resources :likes



  root to: 'gossips#index'
  get '/team', to: 'page#team'
  get '/contact', to: 'page#contact'
  get '/welcome/:first_name', to: 'page#welcome', as: 'welcome'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    validates :name,
        presence: true,
        length: { in: 2..30 }

    validates :zip_code,
        presence: true

    has_many :users 
end

app/models/comment.rb
class Comment < ApplicationRecord

    validates :content,
        presence: true
    
    belongs_to :user
    belongs_to :gossip
    
end

app/models/gossip.rb
class Gossip < ApplicationRecord

    validates :title,
        presence: true, 
        uniqueness: true
        
    validates :content, 
        presence: true

    validates :user, 
        presence: true 

    belongs_to :user
    has_many :comments
    has_many :join_tag_gossips
    has_many :tags, through: :join_tag_gossips
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord

    belongs_to :tag 
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord

    validates :user,
        presence: true

    validates :gossip,
        presence: true 
        
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

    belongs_to :sender, class_name: "User" 
    belongs_to :recipient1, class_name: "User"
    belongs_to :recipient2, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :title,
        presence: true
    
    has_many :join_tag_gossips
    has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord

    validates :first_name,
        presence: true,
        length: { in: 2..20 }

    validates :last_name,
        presence: true,
        length: { in: 2..20 }

    validates :email, 
        presence: true 

    validates :password,
        presence: true, 
        length: { minimum: 4 }


    belongs_to :city
    has_many :gossips
    has_many :comments
    has_many :private_messages, foreign_key: 'sender_id'
    has_many :private_messages, foreign_key: 'recipient1_id'
    has_many :private_messages, foreign_key: 'recipient2_id'
    has_secure_password

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def show 

        @city = Gossip.find(params[:id]).user.city 
        
    end

end

app/controllers/comments_controller.rb
require 'pry'
class CommentsController < ApplicationController

    before_action :authenticate_user, only: [:new, :create]

    def new

        @comment = Comment.new
    end


    def create 

        @comment = Comment.create(content: params_comment[:content],gossip: Gossip.find(params[:gossip_id]), user:current_user)

    end

    def edit
 
        @comment = Comment.find(params[:id])
        @id_comment = @comment.id 

    end

    def update 

        @comment = Comment.find(params[:id])
        @id_gossip = @comment.gossip_id
    
        if @comment = @comment.update(content: params_comment[:content])
        
            
            redirect_to gossip_path(@id_gossip), :notice => "Le commentaire a été modifié " 

        else 
            render :edit
        
        end
    end


    def destroy 
     
        @comment = Comment.all.find(params[:id])
        @comment.destroy 

        redirect_to gossip_path(@comment.gossip_id), :notice => "Le commentaire a été effacé " 
    end



private 

    def params_comment

        return params.require(:comment).permit(:content)

    end

end

app/controllers/gossips_controller.rb
require 'pry'

class GossipsController < ApplicationController

    before_action :authenticate_user, only: [:new, :create, :index]

def new
 
    @gossip = Gossip.new
    
end

def create

    @gossip = Gossip.create(params_gossip)
    @gossip.user = current_user

    if @gossip.save

        flash[:notice] = "Le potin a été sauvé "
        redirect_to gossips_url 

    else 
        flash[:notice] = "Nous n avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :"
        render :new 

    end
  
end

def index

end


def show 

    @gossip = Gossip.find(params[:id])
    @comment = Comment.new 
   
end

def edit 

    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
    end

end


def update 

    @gossip = Gossip.find(params[:id])

    if current_user == @gossip.user

        if @gossip = @gossip.update(params_gossip)
        
            redirect_to gossips_url, :notice => "Le potin a été modifié " 
        else 
            render :edit
        end
    else 
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
    end

end

def destroy
     
    @gossip = Gossip.find(params[:id])
    if current_user == @gossip.user
      
        @gossip.destroy
        @gossip.comments.each do|comment| 
            comment.destroy
        end

        redirect_to gossips_url, :notice => "Le potin a été supprimé"
         
    else
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
       
    end

end


private 

    def params_gossip

        return params.require(:gossip).permit(:title,:content)

    end

    

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def new

    end

    def create

        binding.pry 
        
    end

    def destroy 

    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

    def home 

    end

    def team 

    end

    def contact

    end

    def welcome 

        @first_name = params[:first_name]

    end

    def author 

        @author_first_name = Gossip.find(params[:id]).user.first_name
        @author_last_name = Gossip.find(params[:id]).user.last_name

    end


end

app/controllers/sessions_controller.rb
require 'pry'
class SessionsController < ApplicationController

    def new

    end

    def create

        user = User.find_by(email: params[:email])

        if user && user.authenticate(params[:password])
            
            session[:user_id] = user.id 
            log_in(current_user)
            redirect_to gossips_path 

         else 
            flash[:notice] = "Le profil/mot de passe n'existe pas. Merci de réessayer ou de créer un profil"
            render :new

        end

    end

    def destroy 

        session.delete(:user_id)
        @current_user = nil 
        redirect_to gossips_path
        
    end
    
end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController

    def new 

    @user = User.new 
    
    end

    def create 

        @user = User.create(user_params)
        @user.city = City.first

        if @user.save 

            log_in(@user)
            redirect_to gossips_path, notice => "L'utilisateur a été crée"
        
        else
            
            flash[:notice] = "Erreur dans la création d'un nouvel utilisateur"
            render :new 
       
        end

    end



    def show 
        @gossip = Gossip.find(params[:id])
        @user = Gossip.find(params[:id]).user 
    
    end


    private 

    def user_params 

        return params.require(:user).permit(:first_name,:last_name,:email,:password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        return User.find_by(id: session[:user_id])
    end

    def log_in(user)
      session[:user_id] = user.id
      
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="container">
<h1 class="display-4 text-center my-5">"Edit de commentaires"</h1>

<div class="row justify-content-center">

<%= form_for @comment do |f| %>

  <div class="form-group">

  <label> Contenu du commentaire <label>
  <%= f.text_area :content, class: 'form-control' %>

  </div>
  
  <div class="container">
    <div class="row justify-content-center">
        <div class="form-group">

             <button type="submit"> Updater le commentaire </button> 

        </div>

     <a href =" <%= comment_path(@id_comment)%>" class="btn btn-danger" data-method="DELETE"> Supprimer le commentaire </a>

    </div>
  </div>


<% end %>

 </div>

</div>

app/views/gossips/edit.html.erb
<div class="container">
<h1 class="display-4 text-center my-5">"Edit de gossip"</h1>

<% flash.each do %>

<div class="alert alert-danger text-center">

    <%= notice %>
    <% if @gossip.errors.any? %>
     <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
    </div>
      <% end %>

<div class="row justify-content-center">

<%= form_for @gossip do |f| %>

  <div class="form-group">

  <label> Titre du gossip <label>
  <%= f.text_field :title, class: 'form-control' %>

  </div>

  <div class="form-group">

  <label> Contenu du gossip <label>
  <%= f.text_area :content, class: 'form-control' %>

  </div>

  <div class="form-group">

  <button type="submit"> Updater l'article </button>

  </div>

<% end %>

 </div>

</div>

app/views/gossips/index.html.erb
<div class="container">
  <h1 class="display-4 text-center my-3">The Gossip Project</h1>

  
  <%flash.each do %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% end %>


  <a type="button" class="btn btn-success btn-block" href="<%=new_gossip_path%>"> Créer un potin </a><br><br>

<div class="row">
 <% Gossip.all.each do |gossip| %>
    <div class="col-4 mb-3">
        <div class="card">
          <img class="card-img-top" alt="Card image cap" src="https://lelombrik.net/comment/5eb298012d522.jpg">
          <div class="card-body">
            <h5 class="card-title"><%=gossip.title %></h5>
            <p class="card-text"><%= truncate gossip.content, length: 30 %></p>
            <p class="card-text">
            <small class="text-muted">
              posté par <a href="<%= user_path(gossip.id) %>"><%=gossip.user.first_name %></a>
              le <%=gossip.created_at.strftime("%d/%m/%Y %H:%I") %>
              </small> <br>
              <small class="text-muted"> contient <%=gossip.comments.count%> commentaire(s) </small>
              </p>
            <a type="button" class="btn btn-primary btn-block" href="<%=gossip_path(id: gossip.id) %>">Voir le potin</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>


    

app/views/gossips/new.html.erb
<div class="container">
    <h1 class="display-4 text-center my-5">"Création de gossip"</h1>


    <% flash.each do %>

    <div class="alert alert-danger text-center">
    
      <%= flash[:notice] %>
      <% if @gossip.errors.any? %>
         <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <% end %>

   
    <div class="row justify-content-center">

    <%= form_for @gossip do |f| %>

      <div class="form-group">

      <label> Titre du gossip <label>
      <%= f.text_field :title, class: 'form-control' %>

      </div>

      <div class="form-group">

      <label> Contenu du gossip <label>
      <%= f.text_area :content, class: 'form-control' %>

      </div>

      <div class="form-group">

      <button type="submit"> Créer l'article </button>

      </div>

    <% end %>

     </div>

</div>

app/views/gossips/show.html.erb
<div class="container">
  <h1 class="display-4 text-center my-3">The Gossip number <%=@gossip.id%> </h1>

  <div class="row justify-content-center">
      <div class="col-6">
        <div class="card">
          <img class="card-img-top" alt="Card image cap" src="http://static.hitek.fr/img/actualite/2016/06/27/w_forrestgump2.jpg">
          <div class="card-body">
            <h5 class="card-title"><%=@gossip.title %></h5>
            <p class="card-text"><%= @gossip.content %></p>
            <p class="card-text">
            <p class="card-text">
              <small class="text-muted">
                posté par <a href=" <%= user_path(@gossip.id) %>"><%= @gossip.user.first_name %> </a> venant de <a href="<%= city_path(@gossip.id) %>"><%= @gossip.user.city.name %> </a>
              </small>
            </p>
          </div>
        </div>
      </div>
      </div> <br>   
      <% flash.each do %>
        <div class="alert alert-danger text-center">
        
        <%= flash[:notice] %>        
        </div>
       
    <%end%>
<br>   
  

  <div class="container">
    <div class="row justify-content-center">
      <a href =" <%= edit_gossip_path(@gossip.id) %>" class="btn btn-warning"> Updater l'article </a> 

      <a href =" <%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-method="DELETE"> Supprimer l'article </a>
    </div> 
  </div> 

  <br> 
  <div class="container">
    <div class="row justify-content-center">
      <a href ="<%= likes_path %>" class="btn btn-primary" {id : @gossip.id)}  data-method="POST"> Liker </a>
    </div> 
  </div> 
  <br>
  
  
       
<div class="container">
    <div class="row justify-content-center">
  
      <%= form_for @comment do |f| %>

        <div class="form-group">
          <label> Contenu du commentaire <label>
          <%= f.text_area :content, class: 'form-control' %>
        </div>

        <div class="form-group">
        <button type="submit"> Poster le commentaire </button>
        </div>

        <input name="gossip_id" type="hidden" value="<%=@gossip.id %>" />
      <% end %>

   </div>
</div>

<br> 
<br>

<div class="container">
    <div class="row justify-content-center">
       <table class="table">
            <thead class="thead-dark">
              <tr>
               <th scope="col">ID</th>
                <th scope="col">User</th>
                <th scope="col">Contenu</th>
                <th scope="col"> </th>
              </tr>
            </thead>
            <tbody>
                <% Comment.all.each do |comment| %>
                  <% if comment.gossip_id == @gossip.id %> 

                  <tr>
                    <td><%=comment.id%></td>
                    <td><%=User.find_by(id: comment.user_id).first_name%></td>
                    <td><%=comment.content%></td>
                    <td><a href="<%=edit_comment_path(comment.id)%>"> Modifier le commentaire </a> </td>
                    
                  </tr>
                  <% end %>
                  <% end %>
            </tbody>
        </table>
    </div>
  </div>


  