config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :gossips
  resources :users
  resources :cities
  resources :comments
  resources :sessions
  resources :likes



  root to: 'gossips#index'
  get '/team', to: 'page#team'
  get '/contact', to: 'page#contact'
  get '/welcome/:first_name', to: 'page#welcome', as: 'welcome'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    validates :name,
        presence: true,
        length: { in: 2..30 }

    validates :zip_code,
        presence: true

    has_many :users 
end

app/models/comment.rb
class Comment < ApplicationRecord

    validates :content,
        presence: true
    
    belongs_to :user
    belongs_to :gossip
    
end

app/models/gossip.rb
class Gossip < ApplicationRecord

    validates :title,
        presence: true, 
        uniqueness: true
        
    validates :content, 
        presence: true

    validates :user, 
        presence: true 

    belongs_to :user
    has_many :comments
    has_many :join_tag_gossips
    has_many :tags, through: :join_tag_gossips
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord

    belongs_to :tag 
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord

    validates :user,
        presence: true

    validates :gossip,
        presence: true 
        
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

    belongs_to :sender, class_name: "User" 
    belongs_to :recipient1, class_name: "User"
    belongs_to :recipient2, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :title,
        presence: true
    
    has_many :join_tag_gossips
    has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord

    validates :first_name,
        presence: true,
        length: { in: 2..20 }

    validates :last_name,
        presence: true,
        length: { in: 2..20 }

    validates :email, 
        presence: true 

    validates :password,
        presence: true, 
        length: { minimum: 4 }


    belongs_to :city
    has_many :gossips
    has_many :comments
    has_many :private_messages, foreign_key: 'sender_id'
    has_many :private_messages, foreign_key: 'recipient1_id'
    has_many :private_messages, foreign_key: 'recipient2_id'
    has_secure_password

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def show 

        @city = Gossip.find(params[:id]).user.city 
        
    end

end

app/controllers/gossips_controller.rb
require 'pry'

class GossipsController < ApplicationController

    before_action :authenticate_user, only: [:new, :create, :index]

def new
 
    @gossip = Gossip.new
    
end

def create

    @gossip = Gossip.create(params_gossip)
    @gossip.user = current_user

    if @gossip.save

        flash[:notice] = "Le potin a été sauvé "
        redirect_to gossips_url 

    else 
        flash[:notice] = "Nous n avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :"
        render :new 

    end
  
end

def index

end


def show 

    @gossip = Gossip.find(params[:id])
    @comment = Comment.new 
   
end

def edit 

    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
    end

end


def update 

    @gossip = Gossip.find(params[:id])

    if current_user == @gossip.user

        if @gossip = @gossip.update(params_gossip)
        
            redirect_to gossips_url, :notice => "Le potin a été modifié " 
        else 
            render :edit
        end
    else 
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
    end

end

def destroy
     
    @gossip = Gossip.find(params[:id])
    if current_user == @gossip.user
      
        @gossip.destroy
        @gossip.comments.each do|comment| 
            comment.destroy
        end

        redirect_to gossips_url, :notice => "Le potin a été supprimé"
         
    else
        flash[:notice] = "Cette action n'est pas autorisée."
        redirect_to gossip_path(params[:id])
       
    end

end


private 

    def params_gossip

        return params.require(:gossip).permit(:title,:content)

    end

    

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def new

    end

    def create

        binding.pry 
        
    end

    def destroy 

    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

    def home 

    end

    def team 

    end

    def contact

    end

    def welcome 

        @first_name = params[:first_name]

    end

    def author 

        @author_first_name = Gossip.find(params[:id]).user.first_name
        @author_last_name = Gossip.find(params[:id]).user.last_name

    end


end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController

    def new 

    @user = User.new 
    
    end

    def create 

        @user = User.create(user_params)
        @user.city = City.first

        if @user.save 

            log_in(@user)
            redirect_to gossips_path, notice => "L'utilisateur a été crée"
        
        else
            
            flash[:notice] = "Erreur dans la création d'un nouvel utilisateur"
            render :new 
       
        end

    end



    def show 
        @gossip = Gossip.find(params[:id])
        @user = Gossip.find(params[:id]).user 
    
    end


    private 

    def user_params 

        return params.require(:user).permit(:first_name,:last_name,:email,:password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        return User.find_by(id: session[:user_id])
    end

    def log_in(user)
      session[:user_id] = user.id
      
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href=<%=root_path %>>The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%=root_path %>>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=team_path %>>Team</a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href=<%=contact_path %>>Contact</a>
      </li>
    </ul>
    
    <form class="form-inline my-2 my-lg-0">
    <a class="nav-item nav-link" href=<%=new_user_path %>>Créer un profil</a>
    </form>
    <form class="form-inline my-2 my-lg-0">
    <a class="nav-item nav-link" href=<%=new_session_path %>>Se connecter</a>
    </form>
    <% if current_user %>
    <form class="form-inline my-2 my-lg-0">
    <a class="nav-item nav-link" href=<%=session_path(id: current_user.id) %> data-method="DELETE">Se déconnecter</a>
    </form>
    <% end %>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/page/contact.html.erb
<h1> Contact de l'équipe </h1>

<p> L'équipe est toujours composé de moi, c'est encore et toujours superbe. </p>

app/views/page/team.html.erb
<h1> Présentation de l'équipe </h1>

<p> L'équipe est composé de moi, c'est superbe. </p>

app/views/page/welcome.html.erb
<h1> Bienvenue </h1>

<p> L'équipe qui est composé de moi-même souhaite la bienvenue à <%= @first_name%> ! </p>